### ISSUE TITLE
Impossible to build the corescripts

### ISSUE THREAD

**Issue by niokasgami** [rpgtkoolmv/corescript#109]
Hi peoples, 
I tried right now many times to build the corescript for doing some beta testing but nothing seem to work? 
Just in case I already have a updated version of Node and all I also followed all the steps
I am using visual studio code.

I can't seem to run any of the command and it's throw me errors.
I also tried to build it manually with a GulpFile and the files also throw errors for some reasons.
Here the error-Log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild openmv@1.0.0
6 info build openmv@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info openmv@1.0.0 Failed to exec build script
9 verbose stack Error: openmv@1.0.0 build: `run-p build:*`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid openmv@1.0.0
11 verbose cwd C:\Users\devil\Documents\Test_JS
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error openmv@1.0.0 build: `run-p build:*`
17 error Exit status 1
18 error Failed at the openmv@1.0.0 build script 'run-p build:*'.
18 error This is most likely a problem with the openmv package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     run-p build:*
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs openmv
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls openmv
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Thanks for any further answer.

**Comment by niokasgami** [comment]
Nevermind lol it's seemed that my Node was outdated (although i am sure I updated it...Oh well I guess I didn't updated it correctly)
Closing it.
